#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
#committing out to push to github. giving me errors for now that i will circle back on
#npm exec pretty-quick --staged && npm exec concurrently npm:test npm:lint
